/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ytu.view;

import java.io.IOException;

import javax.swing.JOptionPane;

import org.jsoup.Connection;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

/**
 *
 * @author Administrator
 */
public class Ytdx extends javax.swing.JFrame implements Runnable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -5466469878929220159L;

	/**
     * Creates new form Ytdx
     */
    public Ytdx() {
        initComponents();
        thread = new Thread(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("计费系统查询V5.0");
        setBounds(new java.awt.Rectangle(400, 100, 0, 0));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/ytu/resource/ytdx_ico.jpg")).getImage());
        setResizable(false);

        jTextArea1.setBackground(new java.awt.Color(204, 255, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("幼圆", 0, 12)); // NOI18N
        jLabel1.setText("输入学号到班级，如2011585043");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ytu/resource/button_img.jpg"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(60, 25));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        if (!this.thread.isAlive()) {
            this.thread = new Thread(this);
        }
        try {
            this.thread.start();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "别慌，查询中...");
        }
    }                                        

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ytu/resource/button_enter_img.jpg")));
    }

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ytu/resource/button_img.jpg")));
    }

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ytu/resource/button_click_img.jpg")));
    }

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {
        int key = evt.getKeyCode();
        if (key == 10){
            jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ytu/resource/button_click_img.jpg")));
            if (!this.thread.isAlive()) {
            this.thread = new Thread(this);
            }
            try {
                this.thread.start();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "别慌，查询中...");
            }
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration
    private Thread thread = null;

    private void getImg() {
        String stuunm = this.jTextField1.getText();
        String user = null;

        for (int i = 0; i < 50; ++i) {
            if (i < 10) {
                user = stuunm + "0" + i;
            } else {
                user = stuunm + i;
            }
            String result = getInfo(user);
            if (result.equals("no")) {
                continue;
            }
            if (result.equals("请在烟大校内网登入")) {
                JOptionPane.showMessageDialog(this, "请在烟大校内网使用！");
                break;
            }
            this.jTextArea1.append(result + "\n");
            this.jTextArea1.append("--------------------\n");
        }
        JOptionPane.showMessageDialog(this, "查询结束！");
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ytu/resource/button_img.jpg")));
    }

    public static String getInfo(String user) {
        String url = "http://202.194.116.87/php/user_login.php";

        Connection connection = Jsoup.connect(url);
        connection.timeout(500);
        connection.header("User-Agent", "Mozilla/4.0 (compatible; MSIE 5.0; Windows XP; DigExt)");
        connection.data("loginuser", user);
        connection.data("password", user);
        connection.data("logintype", "连线国内");
        connection.data("refer", "1");
        connection.data("domainid", "2");
        connection.method(Connection.Method.POST);
        try {
            Document doc = connection.post();
            if (doc == null) {
                System.out.println("null");
            }

            Elements links = doc.select("script");

            for (Element e : links) {
                if (e.html().equals("alert('您的帐户余额是5元');")) {
                    return "5元:" + user;
                }

                if (e.html().equals("alert('您的帐户余额是10元');")) {
                    return "10元:" + user;
                }
                e.html().equals("alert('您的帐户余额是0元');");
            }

        } catch (IOException e1) {
            return "请在烟大校内网登入";
        }
        return "no";
    }

    @Override
    public void run() {
        getImg();
    }
}
